from xhtml2pdf import pisa
from io import BytesIO

def create_pdf(data):
    # CSS that adds borders and styles specifically for the PDF
    css = """
    <style>
        @page { size: A4; margin: 2cm; }
        body { font-family: Helvetica, sans-serif; color: #333; line-height: 1.6; }
        h1 { color: #4f46e5; border-bottom: 2px solid #4f46e5; padding-bottom: 10px; }
        h3 { color: #333; margin-top: 25px; border-bottom: 1px solid #ddd; }
        h4 { background-color: #eef2ff; padding: 5px; color: #4f46e5; }
        
        /* FORCE TABLE BORDERS */
        table { width: 100%; border-collapse: collapse; margin-top: 10px; border: 1px solid black; }
        th { background-color: #4f46e5; color: white; padding: 8px; border: 1px solid black; }
        td { padding: 8px; border: 1px solid black; color: #333; }
        
        .stats { background: #ecfdf5; padding: 10px; border: 1px solid #10b981; text-align: center; font-weight: bold; color: #065f46; margin-bottom: 20px; }
    </style>
    """

    html = f"""
    <html>
    <head>{css}</head>
    <body>
        <h1>Personalized Fitness Plan</h1>
        
        <div class="stats">
            BMI: {data.get('bmi')} | Category: {data.get('bmi_category')} | Goal: {data.get('plan_type')}
        </div>

        <div>
            {data.get('ai_html')}
        </div>
        
        <br><hr>
        <div style="text-align: center; color: #888; font-size: 10px;">Generated by AI Fitness Planner</div>
    </body>
    </html>
    """

    pdf_output = BytesIO()
    pisa_status = pisa.CreatePDF(html, dest=pdf_output)
    
    if pisa_status.err: return None
    pdf_output.seek(0)
    return pdf_output